# FROM ubuntu:trusty as build-env

# TODO: Install Python
# TODO: Install Scala
# TODO: Install Spark
# TODO: Install PixieDust
# TODO: Install Install PixieDust (https://pixiedust.github.io/pixiedust/install.html)

# # Install the Jupyter environment
# RUN pip install -U pip && \
# 	pip install -r requirements.txt

# # Setup Pixiedust
# RUN jupyter pixiedust install

# FROM ubuntu:trusty as output

# EXPOSE 8888

# ENTRYPOINT [ "jupyter", "notebook" ]
